name: Quality Assurance
on: [push, pull_request]
jobs:
  assure-quality:
    name: Assure Quality
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Cache modules
      - name: 💻 Set required PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v1
        with:
          modules-to-cache: PSFramework
      - name: 🧰 Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}
      - name: 🤩 Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop

      - name: 👍 Invoke PSSA
        shell: pwsh
        run: |
          ./tests/_pssa.ps1

      - name: ⏬ Install older Pester version
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -MaximumVersion 4.99
          Import-Module -Name Pester -MaximumVersion 4.99

      - name: ✅ Invoke Pester
        shell: pwsh
        run: |
          ./tests/_pester.ps1
