name: Quality Assurance
on: [push, pull_request]
jobs:
  assure-quality:
    strategy:
      matrix:
        PSVer: [pwsh, powershell]
    defaults:
      run:
        shell: ${{ matrix.PSVer }}
    name: Assure Quality - ${{ matrix.PSVer }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Cache modules
      - name: 💻 Set required PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v1
        with:
          modules-to-cache: PSFramework
      - name: 🧰 Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}
      - name: 🤩 Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop

      - name: 👍 Invoke PSScriptAnalyzer
        run: |
          ./tests/_pssa.ps1

      - name: 🧰 Setup PowerShell module cache - Pester
        if: ${{ matrix.PSVer }} == 'pwsh'
        id: cacher-pester
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\Documents\Windows PowerShell\Modules\Pester
          key: Win32NT-${{ matrix.PSVer }}-PSFramework-4.10.1
      - name: 🧰 Setup PowerShell module cache - Pester
        if: ${{ matrix.PSVer }} == 'powershell'
        id: cacher-pester
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\Documents\PowerShell\Modules\Pester
          key: Win32NT-${{ matrix.PSVer }}-PSFramework-4.10.1
      - name: ⏬ Install older Pester version
        if: steps.cacher-pester.outputs.cache-hit != 'true'
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -RequiredVersion 4.10.1 -ErrorAction Stop

      - name: ✅ Invoke Pester
        run: |
          Import-Module -Name Pester -MaximumVersion 4.10.1
          ./tests/_pester.ps1
